name: CI

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: ðŸ›  Setup Node.js environment
        uses: actions/setup-node@v2.1.0
        with:
          node-version: '12.x'
    
      - name: ðŸ“¦ Install dependencies
        run: yarn --frozen-lockfile
      
      - name: âš¡ Build app
        run: yarn build

      - name: ðŸ‘“ Copy build into
        run: |
          git clone https://github.com/bloodzmoon/bloodzmoon.github.io.git tmp
          \cp -fR dist/* tmp/*

      
      - name: âœ¨ Deploy to master
        run: |
          cd tmp
          git config --global user.name ${{secrets.NAME}}
          git config --global user.email ${{secrets.EMAIL}}
          git remote set-url origin https://bloodzmoon:${{secrets.TOKEN}}@github.com/bloodzmoon/bloodzmoon.github.io.git
          git add .
          git commit -m 'ðŸš€ Deploy'
          git push origin master --force